### ISSUE TITLE
Question problem with token 

### ISSUE THREAD

**Issue by rolandporath** [Cloudbet/docs#1]
hello,

i am not able to get data out of the api
this is the token given to me:
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZmZpbGlhdGVfYXBpIiwiZXhwIjoxNTIxNTQ4ODQxLCJpYXQiOjE0OTAwMTI4NDEsImlzcyI6Ind3dy5jbG91ZGJldC5jb20iLCJuYmYiOjE0OTAwMTI4NDEsInN1YiI6ImFmZmlsaWF0ZV9pZF8zNTQ0In0.WMWaqqHTI_JAqTzlxJgCcqBmvtccZCahtN9S_8Djy-o

i get http 403 when hitting https://api.cloudbet.com/api/v1/sports with this token

when i test the token here https://jwt.io/
i get the error message "invalid signature"

thanks

roland porath

**Comment by rolandporath** [comment]
any reply?
anybody out there?
maybe even somebody who can read?

**Comment by kgravenreuth** [comment]
Hi Roland,

Sorry for the delay. Can you email me at klaus.gravenreuth at cloudbet.com

I'll get you added to our slack channel so we can help you resolve the problem faster. Please note I'll be re-generating your token since it's meant to be secret and I've hidden it in the comment above
