### ISSUE TITLE
Price from API in AH market not match the odd

### ISSUE THREAD

**Issue by vuminhquang** [Cloudbet/docs#25]
### Discussed in https://github.com/Cloudbet/docs/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **vuminhquang** April  7, 2022</sup>
Hello,

I used this API to get odds of a match. But don't see the odd.
​/v2​/odds​/events​/{id}

![image](https://user-images.githubusercontent.com/20512463/162207744-c5c67bdf-b85b-4284-9ac9-8eb03655a7d2.png)
What is the field price here?
And the probability: when get 1/0.288 = 3.4. Odd I get from UI is 1.6 only. Please make clear for me. Thank you.

![image](https://user-images.githubusercontent.com/20512463/162207910-0e7eff4d-ad06-416f-9107-acc5a5254023.png)

</div>

**Comment by kgravenreuth** [comment]
Answered in https://github.com/Cloudbet/docs/discussions/24
