### ISSUE TITLE
C# HttpClient 403

### ISSUE THREAD

**Issue by sonderangebot10** [Cloudbet/docs#40]
Hello,

For some weird reason using C# HttpClient I am getting a 403 (forbidden) response. Using python I am getting 200OK on same request. I have tried using NSwag to generate all of the Cloudbet client files, however response is always the same.
![image](https://user-images.githubusercontent.com/37372712/192161124-dd2ad430-bb66-4210-9e25-326ac4423baa.png)
![image](https://user-images.githubusercontent.com/37372712/192161133-e9163076-15fe-4809-9e02-d8618afef362.png)

**Comment by sonderangebot10** [comment]
The issue was that on C# I needed to add user-agent header to browser - is there a specific reason to disallow .net? :(

**Comment by kgravenreuth** [comment]
@sonderangebot10 we do expect the `user-agent` header on all API requests as a basic security feature for our APIs. This is a general requirement. While most languages (e.g. python) and CLI tools (e.g. curl) add the `user-agent` request header automatically, apparently C# may not (as in your case). 

We will mention this requirement in our docs going forward, thanks for bringing it up.

Cheers,
Klaus @ Cloudbet
